/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'www.romanaebanisteria.com' },
      { protocol: 'https', hostname: 'storage.googleapis.com' },
      { protocol: 'https', hostname: 'fontanasrl.odoo.com' },
      { protocol: 'https', hostname: 'i.pinimg.com' },
      { protocol: 'https', hostname: 'm.media-amazon.com' },
      { protocol: 'https', hostname: 'forjaferreatienda.com' },
      { protocol: 'https', hostname: 'naturshome.es' },
      { protocol: 'https', hostname: 'maderahogar.com' },
      { protocol: 'https', hostname: 'encrypted-tbn0.gstatic.com' },
      { protocol: 'https', hostname: 'puertasdesegura.com' },
      { protocol: 'https', hostname: 'shopflamingo.com.mx' },
      { protocol: 'https', hostname: 'camifer.com' },
      { protocol: 'https', hostname: 'www.cajonerasfama.es' },
      { protocol: 'https', hostname: 'www.puertasirati.com' },
      { protocol: 'https', hostname: 'grupocasalima.com' },
      { protocol: 'https', hostname: 'controlaccesosysistemas.com' },
      { protocol: 'https', hostname: 'cr.epaenlinea.com' },
      { protocol: 'https', hostname: 'www.shutterstock.com' },
      { protocol: 'https', hostname: 'www.officedepot.com.mx' },
      { protocol: 'https', hostname: 'nogalbeat.com' },
      { protocol: 'https', hostname: 'www.sempresariales.com' },
      { protocol: 'https', hostname: 'www.puertasyventanasesquivias.com' },
      { protocol: 'https', hostname: 'normo.mx' },
      { protocol: 'https', hostname: 'www.keideamuebles.es' },
      { protocol: 'https', hostname: 'walmartni.vtexassets.com' },
      { protocol: 'https', hostname: 'easycl.vteximg.com.br' },
      { protocol: 'https', hostname: 'image.made-in-china.com' },
      { protocol: 'https', hostname: 'static.ikea.com.do' },
    ],
    domains: [
      'picsum.photos',
      'ochoa.com.do',
      'cdn.sanity.io',
      'comercialdelsol.com.do',
      'scontent-syd2-1.xx.fbcdn.net',
      'chatbot.ewr1.vultrobjects.com',
      'www.romanaebanisteria.com',
      'i.pinimg.com',
      'm.media-amazon.com',
      'forjaferreatienda.com',
      'naturshome.es',
      'maderahogar.com',
      'shopflamingo.com.mx',
      'camifer.com',
      'www.cajonerasfama.es',
      'www.puertasirati.com',
      'grupocasalima.com',
      'controlaccesosysistemas.com',
      'cr.epaenlinea.com',
      'www.shutterstock.com',
      'www.officedepot.com.mx',
      'nogalbeat.com',
      'www.sempresariales.com',
      'www.puertasyventanasesquivias.com',
      'normo.mx',
      'www.keideamuebles.es',
      'walmartni.vtexassets.com',
      'easycl.vteximg.com.br',
      'image.made-in-china.com',
      'static.ikea.com.do',
      'storage.googleapis.com',
  'fontanasrl.odoo.com',
  'encrypted-tbn0.gstatic.com',
  'puertasdesegura.com'
    ],
  },
  i18n: {
      locales: ['en', 'es'],
      defaultLocale: 'es',
      // Añade más configuraciones según sea necesario
  },
  
}

module.exports = nextConfig
